import {createRequire} from 'node:module'
import assert from 'node:assert/strict'
import {writeFile} from 'node:fs/promises'
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright')
const browser=await chromium.launch({headless:true,executablePath:process.env.STAGE_QA_CHROME||undefined,args:['--no-sandbox']})
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],passes=[];page.on('pageerror',e=>errors.push(e.message))
const button=name=>page.getByRole('button',{name,exact:true}),pass=name=>{passes.push(name);console.log('PASS '+name)}
const get=()=>page.evaluate(async()=>{const {db}=await import('/src/db.ts');return (await db.programs.get('stage-qa-legacy')).installation})
const saved=()=>page.waitForFunction(()=>document.querySelector('.stage-save-state')?.textContent==='Enregistré sur cet appareil')
const center=async(selector)=>{const r=await page.locator(selector).first().boundingBox();assert(r);return{x:r.x+r.width/2,y:r.y+r.height/2}}
const clickNode=async(id)=>{const p=await center(`.stage-world [data-node="${id}"]`);await page.mouse.click(p.x,p.y)}
const drag=async(selector,dx,dy)=>{const p=await center(selector);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+dx,p.y+dy,{steps:6});await page.mouse.up();await saved()}
try{
await page.goto('http://127.0.0.1:4173/scripts/stage-qa/index.html?reset=1');await button('Installation avancée').click();await button('Plein écran').click();await button('Adapter à l’écran (F)').click()
await clickNode('piano');await drag('[data-handle="se"]',30,20);assert.ok((await get()).nodes[0].width>120);await page.keyboard.press('Control+z');await saved();assert.equal((await get()).nodes[0].width,120);pass('Resize handle and keyboard Undo')
await drag('[data-handle="rotate"]',40,20);assert.notEqual((await get()).nodes[0].rotation,0);await page.keyboard.press('Control+z');await saved();assert.equal((await get()).nodes[0].rotation,0);pass('Rotation handle and Undo')
await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');await saved();assert.equal((await get()).nodes.length,5);await page.keyboard.press('Delete');await saved();assert.equal((await get()).nodes.length,4);pass('Copy / paste / Delete are scoped to the editor')
await button('Paramètres de scène').click();await page.getByLabel('Pas du magnétisme',{exact:true}).selectOption('0.5');await saved();await clickNode('piano');await drag('.stage-world [data-node="piano"]',36,27);const p=(await get()).nodes[0];assert.ok(Math.abs(p.x/40-Math.round(p.x/40))<1e-6);pass('Grid snapping uses metric coordinates')
await page.keyboard.press('s');await saved();await button('Ajouter accessoire').click();await page.getByLabel('Nom de l’équipement libre',{exact:true}).fill('Pied de saxophone');await button('Placer un équipement libre').click();let rect=await page.locator('.stage-viewport').boundingBox();await page.mouse.click(rect.x+140,rect.y+300);await saved();assert.ok((await get()).nodes.some(n=>n.name==='Pied de saxophone'&&n.layerId==='accessories'));pass('Accessory tool places an independent object on the accessory layer')
await button('Texte / annotation').click();rect=await page.locator('.stage-viewport').boundingBox();await page.mouse.click(rect.x+260,rect.y+290);await saved();assert.ok((await get()).nodes.some(n=>n.kind==='text'));pass('Annotations use their dedicated layer')
await button('Sélection').click();const wire=await page.locator('[data-link="legacy-wire"] path').first().evaluate(el=>{const p=el.getPointAtLength(el.getTotalLength()/2),m=el.getScreenCTM();return{x:p.x*m.a+p.y*m.c+m.e,y:p.x*m.b+p.y*m.d+m.f}});await page.mouse.click(wire.x,wire.y);await button('Courbe').click();await saved();assert.equal((await get()).links[0].routeMode,'curve');await button('Ajouter un point').click();await saved();const route=(await get()).links[0].route;await drag('[data-point="0"]',20,30);assert.notDeepEqual((await get()).links[0].route,route);pass('Cable conversion, bend creation and waypoint drag')
await button('90°').click();await saved();const points=(await get()).links[0].route;await drag('[data-segment="0"]',20,30);assert.notDeepEqual((await get()).links[0].route,points);pass('Cable segment can be moved directly')
await button('Calques').click();await page.getByLabel('Nouveau calque',{exact:true}).fill('Lumières QA');await button('Créer le calque').click();await saved();await button('Isoler Lumières QA').click();await saved();assert.equal(await page.locator('.stage-world [data-stage-layer]').count(),1);await button('Afficher tous les calques').click();await button('Dupliquer Lumières QA').click();await saved();assert.equal((await get()).customLayers.length,3);await button('Fermer les calques').click();pass('Custom layer creation, isolation and duplication')
await button('Historique / Versions').click();await button('Restaurer Version ancienne').click();await saved();assert.equal((await get()).nodes.length,1);await button('Fermer la fenêtre').click();await page.keyboard.press('Control+z');await saved();assert.ok((await get()).nodes.length>1);pass('Restore a legacy version then Undo the restoration')
await button('Aperçu avant export').click();await page.getByLabel('Mode d’export',{exact:true}).selectOption('separate');await button('Générer l’aperçu').click();await page.locator('.stage-export-preview img').first().waitFor({timeout:60000});assert.equal(await page.locator('.stage-export-preview img').count(),(await get()).customLayers.length+7);pass('Separate PNG exports for all chosen layers');await button('Fermer la fenêtre').click()
const persisted=await get();await page.goto('http://127.0.0.1:4173/scripts/stage-qa/index.html');await button('Installation avancée').click();await page.locator('.stage-world').waitFor();assert.deepEqual(await get(),persisted);pass('Reload preserves the saved plan')
assert.deepEqual(errors,[]);await writeFile('/tmp/diart-stage-results/commands-report.json',JSON.stringify({passes,errors},null,2))
}catch(e){console.error(e);console.log(errors);await page.screenshot({path:'/tmp/diart-stage-results/commands-failure.png'});process.exitCode=1}finally{await browser.close()}
