import {createRequire} from 'node:module'
import {mkdir,writeFile} from 'node:fs/promises'
import assert from 'node:assert/strict'
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright')
const output='/tmp/diart-scenography-results';await mkdir(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:process.env.STAGE_QA_CHROME||undefined,args:['--no-sandbox']})
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[],steps=[]
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('example.invalid'))requests.push(r.url())})
const button=name=>page.getByRole('button',{name,exact:true}),pass=name=>{steps.push(name);console.log('PASS '+name)}
const programs=()=>page.evaluate(async()=>{const {db}=await import('/src/db.ts');return db.programs.toArray()})
const get=async()=>(await programs()).find(p=>p.id==='stage-qa-legacy').installation
const saved=()=>page.waitForFunction(()=>document.querySelector('.stage-save-state')?.textContent==='Enregistré sur cet appareil')
const world=async(x,y)=>{const r=await page.locator('.stage-world').boundingBox(),p=await get();return{x:r.x+x*r.width/p.stageWidth,y:r.y+y*r.height/p.stageHeight}}
const clickWorld=async(x,y)=>{const p=await world(x,y);await page.mouse.click(p.x,p.y)}
const clickNode=async id=>{const n=(await get()).nodes.find(n=>n.id===id);await clickWorld(n.x+n.width/2,n.y+n.height/2)}
const fill=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(String(value));await page.getByLabel(label,{exact:true}).press('Tab');await saved()}
const add=async(name,x,y)=>{await button('Ajouter un objet visuel').click();await page.getByLabel('Rechercher un objet',{exact:true}).fill(name);await page.locator('.stage-object-card').filter({hasText:name}).first().click();await clickWorld(x,y);await saved();return (await get()).nodes.at(-1).id}
const logo='<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><script>throw new Error("IMPORTED_SCRIPT")</script><image href="https://example.invalid/pixel"/><rect x="10" y="10" width="380" height="280" rx="20" fill="#e5ece9" stroke="#2b555c" stroke-width="6"/><path d="M90 215L200 65L310 215Z" fill="#507e79"/><text x="200" y="260" text-anchor="middle" font-family="Arial" font-size="26" fill="#24434d">ATELIER</text></svg>'
const svg={name:'Atelier.svg',mimeType:'image/svg+xml',buffer:Buffer.from(logo)}
try{
await page.goto('http://127.0.0.1:4173/scripts/stage-qa/index.html?reset=1');await button('Installation avancée').click();await button('Plein écran').click();await button('Adapter à l’écran (F)').click()
const legacy=await get();await button('Présentation client').click();await saved();assert.equal(await page.locator('.stage-world [data-link]').count(),0);assert.deepEqual((await get()).nodes,legacy.nodes);assert.deepEqual((await get()).links,legacy.links);await button('Hybride').click();await saved();assert.ok(await page.locator('.stage-world [data-link]').count()>0);await button('Technique').click();await saved();pass('Technical, hybrid and client share exact node coordinates and cable data')
await clickNode('mic');await button('Représentation : Micro sur pied perche').click();await saved();const changed=await get();assert.equal(changed.nodes[1].stockItemId,'qa-mic');assert.deepEqual(changed.links,legacy.links);assert.equal(changed.nodes[1].appearance.illustration,'mic-boom');pass('Microphone variant changes appearance without changing stock or wiring')
const chair=await add('Chaise simple',570,360);assert.equal((await get()).nodes.find(n=>n.id===chair).visualOnly,true);assert.equal((await get()).nodes.find(n=>n.id===chair).stockItemId,undefined);pass('Searchable visual gallery places an unassociated chair at a metric size')
await page.locator('.stage-inspector summary').filter({hasText:'Matériel & stock'}).click();await button('Associer au matériel').click();await page.getByLabel('Matériel à associer',{exact:true}).selectOption('qa-chair');await page.getByLabel('Quantité à associer',{exact:true}).fill('40');await button('Associer cet objet').click();await saved();assert.equal((await get()).nodes.find(n=>n.id===chair).quantity,40);assert.equal((await get()).nodes.find(n=>n.id===chair).visualOnly,false);assert.equal(await page.evaluate(async()=>{const {db}=await import('/src/db.ts');return(await db.inventoryStock.get('qa-chair')).quantity}),80);pass('Stock association represents 40 chairs while physical inventory remains 80')
await button('Représentation : Tabouret').click();await saved();assert.equal((await get()).nodes.find(n=>n.id===chair).stockItemId,'qa-chair');await button('Représentation : Chaise simple').click();await saved();await fill('Largeur (m)',.6);let n=(await get()).nodes.find(n=>n.id===chair);assert.equal(n.width,n.height);pass('Variant and aspect-locked resizing preserve technical identity')
// Use a separate unassociated chair so series quantities stay explicit.
const rowChair=await add('Chaise simple',100,520);await button('Dupliquer en série').click();await page.getByLabel('Nombre total',{exact:true}).fill('12');await page.getByLabel('Colonnes',{exact:true}).fill('4');await page.getByLabel('Espacement horizontal (m)',{exact:true}).fill('.15');await button('Créer la série').click();await saved();const grid=await get();assert.equal(grid.nodes.length,17);await button('Annuler (Ctrl+Z)').click();await saved();assert.equal((await get()).nodes.length,6);await button('Rétablir (Ctrl+Y)').click();await saved();assert.equal((await get()).nodes.length,17);pass('Twelve chairs in a 4 × 3 grid with transactional Undo / Redo')
await button('Sélection').click();await clickNode('piano');await page.keyboard.down('Shift');await clickNode('mic');await page.keyboard.up('Shift');await button('Grouper').click();await saved();await fill('Nom du groupe','Poste pianiste');const grouped=await get();assert.equal(grouped.groups.length,1);await clickNode('piano');assert.match(await page.locator('.stage-status').innerText(),/2 sélectionné/);const start=await world(grouped.nodes[0].x+60,grouped.nodes[0].y+45);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x+35,start.y+25,{steps:8});await page.mouse.up();await saved();let after=await get();assert.ok(Math.abs((after.nodes[0].x-grouped.nodes[0].x)-(after.nodes[1].x-grouped.nodes[1].x))<1e-6);pass('Named persistent group selects and moves all its members')
await button('Verrouiller le groupe').click();await saved();const frozen=await get();await clickNode('piano');await page.mouse.move(start.x+35,start.y+25);await page.mouse.down();await page.mouse.move(start.x+80,start.y+60,{steps:5});await page.mouse.up();await saved();assert.deepEqual((await get()).nodes,frozen.nodes);await button('Déverrouiller le groupe').click();await saved();pass('Group locking prevents movement')
await button('Enregistrer dans Mes objets').click();await page.getByLabel('Nom du bloc',{exact:true}).fill('Poste pianiste QA');await button('Enregistrer le bloc').click();await page.getByRole('dialog').waitFor({state:'hidden'});const block=(await programs()).find(p=>p.templateKind==='block');assert.ok(block);assert.equal(block.installation.nodes.length,2);await button('Ajouter un objet visuel').click();await button('Mes objets').click();await page.locator('.stage-object-card').filter({hasText:'Poste pianiste QA'}).click();await clickWorld(680,460);await saved();assert.equal((await get()).groups.length,2);assert.equal(new Set((await get()).nodes.map(n=>n.id)).size,(await get()).nodes.length);assert.deepEqual((await programs()).find(p=>p.id===block.id),block);pass('Reusable personal block inserts independent nodes and group IDs')
await button('Ajouter un objet visuel').click();await page.locator('.stage-object-library input[type=file]').setInputFiles(svg);await page.locator('.stage-object-card').filter({hasText:'Atelier'}).waitFor();const personal=(await programs()).find(p=>p.name==='Atelier');assert.ok(Object.values(personal.installation.assets)[0].dataUrl.startsWith('data:image/png;'));assert.deepEqual(requests,[]);await page.locator('.stage-object-card').filter({hasText:'Atelier'}).click();await clickWorld(740,40);await saved();assert.equal((await get()).nodes.at(-1).appearance.illustration,'imported');pass('SVG import is self-contained, inert and reusable in Mes objets')
await button('Ajouter un objet visuel').click();await page.getByLabel('Rechercher un objet',{exact:true}).fill('Plante');const card=page.locator('.stage-object-card').filter({hasText:'Plante'}).first();const target=await world(450,330);await card.dragTo(page.locator('.stage-viewport'),{targetPosition:{x:target.x-(await page.locator('.stage-viewport').boundingBox()).x,y:target.y-(await page.locator('.stage-viewport').boundingBox()).y}});await saved();assert.equal((await get()).nodes.at(-1).appearance.illustration,'plant');pass('Desktop drag and drop places a library silhouette directly')
await button('Paramètres de scène').click();await page.locator('.stage-inspector summary').filter({hasText:'Plan / photo de salle'}).click();await page.locator('.stage-inspector input[type=file]').setInputFiles(svg);await button('Calibrer une distance connue').waitFor();await saved();const bgBefore=(await get()).backgroundImage;await button('Calibrer une distance connue').click();await clickWorld(50,50);await clickWorld(250,50);await page.getByLabel('Distance connue (m)',{exact:true}).fill('5');await button('Appliquer la calibration').click();await saved();assert.ok(Math.abs((await get()).backgroundImage.width-bgBefore.width*2)<1);pass('Reference plan import and two-point metric calibration preserve objects')
const persisted=await get();await page.goto('http://127.0.0.1:4173/scripts/stage-qa/index.html');await button('Installation avancée').click();await page.locator('.stage-world').waitFor();assert.deepEqual(await get(),persisted);assert.ok((await programs()).some(p=>p.name==='Poste pianiste QA'));pass('Reload keeps appearances, groups, personal assets and background calibration')
// A clear, reproducible 5 × 4 m client scenario, assembled from the real catalog.
await page.evaluate(async()=>{const {db}=await import('/src/db.ts'),{createVisualNode}=await import('/src/stage/ObjectLibrary.tsx');const installation={nodes:[],links:[],stageWidth:750,stageHeight:600,stageWidthMeters:5,stageDepthMeters:4,stagePixelsPerMeter:150,viewMode:'client',background:'#f1f2ee',presentation:{client:'Atelier Événements',title:'Concert privé · implantation',date:'05 octobre 2026',location:'Salle Horizon',version:'A'}};const list=[['led-wall',1.05,.15,'ÉCRAN LED',0],['keyboard',.35,1.25,'PIANO',0],['chair',.8,1.75,'',0],['drums',2.9,.7,'BATTERIE',0],['mic-boom',1.35,1.4,'',0],['speaker',.15,2.9,'Façade G',0],['speaker',4.35,2.9,'Façade D',0],['wedge',.8,2.6,'',0],['wedge',1.8,2.6,'',0],['wedge',2.8,2.6,'',0],['wedge',3.8,2.6,'',0],['singer',1.4,2.08,'CHANT',0],['singer',2.3,2.08,'CHANT',0],['singer',3.2,2.08,'CHANT',0],['mic-straight',1.46,2.47,'',0],['mic-straight',2.36,2.47,'',0],['mic-straight',3.26,2.47,'',0],['plant',.14,.17,'',0],['plant',4.22,.17,'',0]];for(const [id,x,y,label,rotation]of list){const n=createVisualNode(id,installation,{x:x*150,y:y*150});n.rotation=rotation;n.appearance.labelMode=label?'custom':'none';n.appearance.customLabel=label;n.appearance.labelSize=11;installation.nodes.push(n)}installation.nodes[0].stockItemId='qa-stock';installation.nodes[0].visualOnly=false;installation.links=[{id:'demo-wire',fromNodeId:installation.nodes[1].id,toNodeId:installation.nodes[5].id,kind:'audio',assignedChannel:'CH-SECRET',label:'INTERNAL',lengthMeters:10}];await db.programs.update('stage-qa-legacy',{name:'Concert Horizon',installation})})
await page.goto('http://127.0.0.1:4173/scripts/stage-qa/index.html');await button('Installation avancée').click();await button('Plein écran').click();await button('Fermer les propriétés').click();await button('Adapter à l’écran (F)').click();await page.screenshot({path:output+'/scene-client-desktop.png'});pass('Expected 5 × 4 m scenario renders silhouettes with the technical graph intact')
await button('Aperçu client').click();assert.equal(await page.getByLabel('Câbles',{exact:true}).isChecked(),false);assert.equal(await page.getByLabel('Références techniques',{exact:true}).isChecked(),false);assert.equal(await page.getByLabel('Noms prestataires',{exact:true}).isChecked(),false);assert.equal(await page.getByLabel('Numéros de canaux',{exact:true}).isChecked(),false);await page.locator('.stage-export-options input[type=file]').setInputFiles(svg);await button('Générer l’aperçu').click();await page.locator('.stage-export-preview img').waitFor({timeout:60000});const png=await page.locator('.stage-export-preview img').getAttribute('src');assert.equal(await page.getByRole('link',{name:'Télécharger PNG',exact:true}).getAttribute('href'),png);await writeFile(output+'/presentation-client.png',Buffer.from(png.split(',')[1],'base64'));const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Télécharger PDF',exact:true}).click()]);await download.saveAs(output+'/presentation-client.pdf');await page.screenshot({path:output+'/export-client-desktop.png'});pass('Client defaults hide internal data and PNG/PDF download from the exact preview')
await page.getByLabel('Composition de l’export',{exact:true}).selectOption('plan');await button('Générer l’aperçu').click();await page.locator('.stage-export-preview img').waitFor({timeout:60000});await writeFile(output+'/plan-only.png',Buffer.from((await page.locator('.stage-export-preview img').getAttribute('src')).split(',')[1],'base64'));pass('Plan-only export omits the presentation sheet')
await button('Fermer la fenêtre').click();await page.evaluate(()=>document.documentElement.dataset.theme='light');await button('Ajouter un objet visuel').click();await page.screenshot({path:output+'/library-light.png'});await button('Fermer la bibliothèque').click();await page.evaluate(()=>document.documentElement.dataset.theme='dark');
for(const [name,width,height]of [['tablet',1024,768],['phone',390,844]]){await page.setViewportSize({width,height});await button('Adapter à l’écran (F)').click();await button('Ajouter un objet visuel').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:output+'/library-'+name+'.png'});await button('Fermer la bibliothèque').click();await button('Adapter à l’écran (F)').click();await page.screenshot({path:output+'/scene-'+name+'.png'});pass(name+' viewport has an accessible gallery and no horizontal page overflow')}
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);pass('No runtime errors or external requests from imported SVG')
await writeFile(output+'/report.json',JSON.stringify({browser:await browser.version(),steps,errors},null,2))
}catch(error){console.error(error);console.log('ERRORS',errors);await page.screenshot({path:output+'/failure.png'});await writeFile(output+'/failure.txt',await page.locator('body').innerText());process.exitCode=1}finally{await browser.close()}
