import { describe,it,expect } from 'vitest'
import { alignSelection,cableDistance,changeMetrics,clone,copyProgram,duplicateSelection,geometry,HistoryManager,linkPoints,moveSelection,planVersion,restoreVersion,type Plan } from './model'
import type { InventoryProgram } from '../types'

const legacy=():Plan=>({nodes:[{id:'a',name:'Piano',x:100,y:100,stockItemId:'stock',rotation:30},{id:'b',name:'MR18',x:400,y:200}],links:[{id:'wire',fromNodeId:'a',toNodeId:'b',kind:'audio',routeMode:'zigzag',route:[{x:250,y:142},{x:250,y:242}],lengthMeters:10}],stageWidth:1000,stageHeight:800,stageWidthMeters:10,stageDepthMeters:8,stagePixelsPerMeter:100,customLayers:[{id:'custom-one',name:'Lumière'}],layerOrder:['custom-one','materials','audio'],snapshots:[{id:'old',name:'Plan initial',nodes:[{id:'old-a',name:'Micro'}],links:[],createdAt:'2026-10-01T00:00:00Z'}]})
describe('Stage document compatibility and transactions',()=>{
  it('opens old nodes without discarding optional routes, dimensions, layers or versions',()=>{const p=legacy(),n=geometry(p.nodes[0]);expect(n).toMatchObject({x:100,y:100,width:110,height:84,rotation:30});expect(p.snapshots).toHaveLength(1);expect(p.links[0].route).toHaveLength(2)})
  it('keeps a complete group drag in one undo step and supports redo',()=>{const p=legacy(),history=new HistoryManager();const result=moveSelection(p,['a','b'],{x:100,y:50});history.record(p,result);expect(history.past).toHaveLength(1);expect(result.links[0].route?.[0]).toEqual({x:350,y:192});expect(history.undo(result)).toEqual(p);expect(history.redo(p)).toEqual(result)})
  it('records creation, deletion and property changes with a bounded history',()=>{const h=new HistoryManager(80);let p=legacy();for(let i=0;i<100;i++){const next={...p,stageWidth:1001+i};h.record(p,next);p=next}expect(h.past).toHaveLength(80);const undo=h.undo(p);h.record(undo,{...undo,stageWidth:900});expect(h.future).toHaveLength(0)})
  it('never moves locked objects or locked layers',()=>{const p=legacy();p.nodes[0].locked=true;p.nodes[1].layerId='custom-one';p.layerLocks={'custom-one':true};expect(moveSelection(p,['a','b'],{x:100,y:50})).toEqual(p)})
  it('duplicates internal cables with new endpoints and nested arrays',()=>{const p=legacy(),r=duplicateSelection(p,['a','b']);expect(r.ids).toHaveLength(2);expect(r.plan.links[1].fromNodeId).toBe(r.ids[0]);expect(r.plan.nodes[2].stockItemId).toBe('stock');r.plan.links[1].route![0].x=999;expect(p.links[0].route![0].x).toBe(250)})
  it('adapts positions, dimensions and cable waypoints proportionally',()=>{const p=legacy(),r=changeMetrics(p,5,4,100,true);expect(r.stageWidth).toBe(500);expect(r.nodes[0]).toMatchObject({x:50,y:50,width:55,height:42,rotation:30});expect(r.links[0].route?.[0]).toEqual({x:125,y:71});expect(r.links[0].lengthMeters).toBe(10)})
  it('measurement-only changes preserve exact geometry, working area and routes',()=>{const p=legacy(),r=changeMetrics(p,5,4,75,false);expect(r.nodes).toEqual(p.nodes);expect(r.links).toEqual(p.links);expect(r.stagePixelsPerMeter).toBe(75);expect(r.stageWidth).toBe(1000)})
  it('restores full new versions and compatible legacy versions without losing the version library',()=>{const p=legacy(),v=planVersion(p,'Concert'),other=changeMetrics(p,20,16,100,true);other.snapshots=[...p.snapshots!,v];const restored=restoreVersion(other,v);expect(restored.nodes).toEqual(p.nodes);expect(restored.stageWidth).toBe(p.stageWidth);expect(restored.snapshots).toHaveLength(2);const old=restoreVersion(other,p.snapshots![0]);expect(old.nodes[0].name).toBe('Micro');expect(old.stageWidth).toBe(2000)})
  it('copies programs and templates without shared arrays or stock mutations',()=>{const p:InventoryProgram={id:'program',name:'Concert',date:'2026-10-05',frequency:'weekly',location:'Église',notes:'Balance',items:[{id:'item',name:'Piano',category:'instrument',quantity:1,stockItemId:'stock',loaded:true,returned:true}],installation:legacy(),isPublic:true,createdAt:'',updatedAt:'',deletedAt:null};const copy=copyProgram(p,'Concert 12','2026-10-12','complete');expect(copy.isPublic).toBe(false);expect(copy.items[0]).toMatchObject({stockItemId:'stock',quantity:1,loaded:false,returned:false});copy.installation!.links[0].route![0].x=999;copy.installation!.snapshots![0].nodes[0].name='Changed';expect(p.installation!.links[0].route![0].x).toBe(250);expect(p.installation!.snapshots![0].nodes[0].name).toBe('Micro');expect(copyProgram(p,'Plan','','plan').items).toEqual([]);expect(copyProgram(p,'Modèle','','complete',true)).toMatchObject({date:'',frequency:'once',isTemplate:true})})
  it('calculates metric cable lengths along orthogonal paths without replacing manual values',()=>{const p=legacy(),points=linkPoints(p,p.links[0]);expect(points.every((q,i)=>!i||q.x===points[i-1].x||q.y===points[i-1].y)).toBe(true);expect(cableDistance(p,p.links[0])).toBeCloseTo(4);expect(p.links[0].lengthMeters).toBe(10)})
  it('estimates curves longer than their chord',()=>{const p=legacy();p.links[0]={...p.links[0],routeMode:'curve',route:[{x:300,y:0}]};expect(cableDistance(p,p.links[0])).toBeGreaterThan(Math.hypot(300,100)/100)})
  it('aligns and distributes only editable objects',()=>{const p=legacy();p.nodes.push({id:'c',name:'Micro',x:700,y:450,width:70,height:60});const q=alignSelection(p,['a','b','c'],'top');expect(q.nodes.map(n=>n.y)).toEqual([100,100,100]);const r=alignSelection(q,['a','b','c'],'horizontal');const gs=r.nodes.map(geometry);expect(gs[1].x-gs[0].x-gs[0].width).toBeCloseTo(gs[2].x-gs[1].x-gs[1].width);expect(p.nodes[2].y).toBe(450)})
})
