import { describe,it,expect } from 'vitest'
import type { InventoryStockItem } from '../types'
import { copyProgram,duplicateSelection,expandGroups,groupSelection,insertBlock,linkLocked,metrics,moveSelection,seriesSelection,stockNeeds,type Plan,type SeriesOptions,changeMetrics } from './model'
import { inferIllustration,nodeLabel } from './catalog'
const plan=():Plan=>({nodes:[{id:'a',name:'Shure SM58 · ARIZONA',stockItemId:'mic-stock',x:80,y:100,width:40,height:40,appearance:{illustration:'mic-boom',shortLabel:'Chant'}},{id:'b',name:'Chaise client',kind:'visual',visualOnly:true,x:150,y:100,width:40,height:40,appearance:{illustration:'chair'}}],links:[{id:'l',fromNodeId:'a',toNodeId:'b',kind:'accessory',route:[{x:140,y:120}]}],stagePixelsPerMeter:100,stageWidth:500,stageHeight:400})
const series:SeriesOptions={count:12,layout:'grid',columns:4,gapX:.2,gapY:.3,rotation:0,radius:2,arc:120}
describe('Scenography on a single technical graph',()=>{
 it('infers old equipment silhouettes without changing legacy identity',()=>{const p=plan(),before=structuredClone(p);expect(inferIllustration({id:'',name:'Yamaha piano à queue'})).toBe('grand-piano');expect(inferIllustration(p.nodes[0])).toBe('mic-boom');expect(p).toEqual(before)})
 it('keeps unassociated scenery out of stock needs and counts represented quantities',()=>{const p=plan();expect([...stockNeeds(p)]).toEqual([['mic-stock',1]]);p.nodes[1]={...p.nodes[1],stockItemId:'chair-stock',visualOnly:false,quantity:40};expect(stockNeeds(p).get('chair-stock')).toBe(40);p.nodes[1].appearance={illustration:'stool',color:'#ff0000'};expect(stockNeeds(p).get('chair-stock')).toBe(40);expect(p.links[0].fromNodeId).toBe('a')})
 it('selects persistent groups and respects both object and internal cable locks',()=>{let p=groupSelection(plan(),['a','b'],'Poste chant');expect(expandGroups(p,['a'])).toEqual(['a','b']);p.groups![0].locked=true;expect(moveSelection(p,expandGroups(p,['b']),{x:100,y:0})).toEqual(p);expect(linkLocked(p,p.links[0])).toBe(true);expect(seriesSelection(p,['a','b'],series).plan).toBe(p)})
 it('duplicates groups and wires with independent IDs while preserving stock references',()=>{const p=groupSelection(plan(),['a','b'],'Poste chant'),r=duplicateSelection(p,['a','b']);expect(r.plan.groups).toHaveLength(2);expect(r.plan.groups![1].nodeIds).toEqual(r.ids);expect(r.plan.links[1].fromNodeId).toBe(r.ids[0]);expect(r.plan.nodes[2].stockItemId).toBe('mic-stock');expect(r.plan.nodes[3].visualOnly).toBe(true)})
 it('builds 4 × 3 with edge spacing, preserves original IDs and external links',()=>{const p=plan();p.links=[];const r=seriesSelection(p,['b'],series);expect(r.ids).toHaveLength(12);expect(new Set(r.ids).size).toBe(12);expect(r.ids[0]).toBe('b');const copies=r.plan.nodes.filter(n=>r.ids.includes(n.id));expect(copies.map(n=>n.x)).toEqual([150,210,270,330,150,210,270,330,150,210,270,330]);expect(copies.map(n=>n.y)).toEqual([100,100,100,100,170,170,170,170,240,240,240,240]);expect(stockNeeds(r.plan).get('mic-stock')).toBe(1)})
 it('rotates complete series blocks and their cable routes together',()=>{const p=groupSelection(plan(),['a','b'],'Poste'),r=seriesSelection(p,['a','b'],{...series,count:3,rotation:90});expect(r.plan.groups).toHaveLength(3);expect(r.plan.links).toHaveLength(3);expect(r.plan.nodes.every(n=>n.rotation===90)).toBe(true);for(const g of r.plan.groups!)expect(g.nodeIds.every(id=>r.plan.nodes.some(n=>n.id===id))).toBe(true);expect(p.nodes[0].x).toBe(80)})
 it('creates a full circle with distinct positions at the specified radius',()=>{const r=seriesSelection(plan(),['b'],{...series,layout:'circle',count:8,radius:2});const nodes=r.plan.nodes.filter(n=>r.ids.includes(n.id));const center={x:170,y:320};for(const n of nodes)expect(Math.hypot(n.x!+20-center.x,n.y!+20-center.y)).toBeCloseTo(200);expect(new Set(nodes.map(n=>n.x+','+n.y)).size).toBe(8)})
 it('inserts reusable blocks in metric scale and remaps imported asset collisions',()=>{const source=groupSelection(plan(),['a','b'],'Poste');source.assets={img:{id:'img',name:'Logo',dataUrl:'data:image/png;base64,AA',width:100,height:100}};source.nodes[1].appearance={imageId:'img',illustration:'imported'};const destination:Plan={nodes:[],links:[],stagePixelsPerMeter:50,assets:{img:{id:'img',name:'Other',dataUrl:'data:image/png;base64,BB',width:100,height:100}}};const r=insertBlock(destination,source,{x:200,y:300});expect(r.plan.nodes[0]).toMatchObject({x:200,y:300,width:20,height:20});expect(r.plan.nodes[1].appearance!.imageId).not.toBe('img');expect(r.plan.assets!.img.name).toBe('Other');expect(r.plan.assets![r.plan.nodes[1].appearance!.imageId!].name).toBe('Logo');expect(r.plan.groups![0].nodeIds).toEqual(r.ids);expect(r.plan.links[0].fromNodeId).toBe(r.ids[0])})
 it('requires export opt-ins for material references and provider names',()=>{const p=plan(),stock={id:'mic-stock',name:'Shure SM58',provider:'PRIVATE PROVIDER'} as InventoryStockItem;expect(nodeLabel(p.nodes[0],stock,'client')).toBe('Chant');for(const labelMode of ['full','material'] as const){const n={...p.nodes[0],appearance:{...p.nodes[0].appearance,labelMode}};expect(nodeLabel(n,stock,'client')).toBe('Chant')};expect(nodeLabel(p.nodes[0],stock,'client',true,true)).toContain('PRIVATE PROVIDER');expect(nodeLabel(p.nodes[0],stock,'technical')).toContain('Shure')})
 it('adapts a reference image only when adapting geometry',()=>{const p=plan();p.backgroundImage={imageId:'image',x:10,y:10,width:300,height:200,opacity:.6,locked:true};const a=changeMetrics(p,10,8,100,true),b=changeMetrics(p,10,8,100,false);expect(a.backgroundImage).toMatchObject({x:20,y:20,width:600,height:400});expect(b.backgroundImage).toEqual(p.backgroundImage);expect(metrics(b).width).toBe(500)})
})
